ARDUINO_DIR  = /usr/share/arduino

TARGET = Teclado/SourceCode/keyboard.ino

BOARD_TAG    = Leonardo
ARDUINO_PORT = /dev/ttyACM0  # change this to the port used by your board

#ARDUINO_LIBS = WIRE
#ARDUINO_LIBS += DS3231

ARDUINO_DIR  = /usr/share/arduino
AVR_TOOLS_PATH = /usr/bin

include /usr/share/arduino/Arduino.mk
